version: "3.4"

services:
  client:
    image: ${GITHUB_USERNAME-rep}/atir-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 8080
      MONGO_URL: $MONGO_URL
      ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
    ports:
      - "9090:8080"
    volumes:
      - "/etc/hosts:/etc/hosts"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
