export { default as userRoutes } from './userRoutes.js'
export { default as productRoutes } from './productRoutes.js'
export { default as orderRoutes } from './orderRoutes.js'
export { default as purchasedProductRoutes } from './purchasedProductRoutes.js'
export { default as productGroupRoutes } from './productGroupRoutes.js'
export { default as settingRoutes } from './settingRoutes.js'
